In [106]:
# necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [107]:
v=pd.read_csv('/content/Superstore (2).csv',encoding='ISO-8859-1')

In [108]:
 v.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [109]:
# first we will check for null values
v.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [110]:
# for order date and ship date dtype is object but we need datetime

In [111]:
v.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

# Data Preprocessing

In [112]:
# checking for null values,duplicate values,dtypes
v.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [113]:
v.drop_duplicates()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [114]:
v

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [115]:
v.dtypes   # order date and ship date dtype has to be datetime change that

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [116]:

v['Order Date']=pd.to_datetime(v['Order Date'],dayfirst=True,errors="coerce")
v['Ship Date']=pd.to_datetime(v['Ship Date'],dayfirst=True,errors="coerce")

In [117]:
v.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [118]:
v

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [119]:
v['Delivery time'] =(v['Ship Date']-v['Order Date'])
 # by deafult it gives in days...
v

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Delivery time
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3 days
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3 days
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4 days
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7 days
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2 days
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,5 days
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,5 days
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,5 days
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,5 days

#  1) find profit margin by category  and sub categroy

In [120]:
# extracting  new column month and year from order date

In [121]:
v['year']=v['Order Date'].dt.year
v['month']=v['Order Date'].dt.month

In [122]:
v

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Delivery time,year,month
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3 days,2016,11
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3 days,2016,11
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4 days,2016,6
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7 days,2015,10
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7 days,2015,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,2 days,2014,1
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,5 days,2017,2
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,5 days,2017,2
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,5 days,2017,2
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,5 days,2017,5

In [123]:
v.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Delivery time', 'year', 'month'],
      dtype='object')

# 1) Which product categories and sub-categories generate the highest and lowest profit margins?

In [124]:
catprofit=v.groupby(['Category','Sub-Category'])[['Sales','Profit']].sum().reset_index()
print("\n1. Profit margins by category and sub-category")
print(catprofit)

1. Profit margins by category and sub-category
           Category Sub-Category        Sales      Profit
0         Furniture    Bookcases  114879.9963  -3472.5560
1         Furniture       Chairs  328449.1030  26590.1663
2         Furniture  Furnishings   91705.1640  13059.1436
3         Furniture       Tables  206965.5320 -17725.4811
4   Office Supplies   Appliances  107532.1610  18138.0054
5   Office Supplies          Art   27118.7920   6527.7870
6   Office Supplies      Binders  203412.7330  30221.7633
7   Office Supplies    Envelopes   16476.4020   6964.1767
8   Office Supplies    Fasteners    3024.2800    949.5182
9   Office Supplies       Labels   12486.3120   5546.2540
10  Office Supplies        Paper   78479.2060  34053.5693
11  Office Supplies      Storage  223843.6080  21278.8264
12  Office Supplies     Supplies   46673.5380  -1189.0995
13       Technology  Accessories  167380.3180  41936.6357
14       Technology      Copiers  149528.0300  55617.8249
15       Technology     Machines  189238.6310   3384.7569
16       Technology       Phones  330007.0540  44515.7306

# Which states or regions contribute most to overall sales and profits?

In [125]:
profit = v.groupby(['State','Region'])[['Sales', 'Profit']].sum().reset_index()
print("\n2. Profit by state and regions")
print(profit)

2. Profit by state and regions
                   State   Region        Sales      Profit
0                Alabama    South   19510.6400   5786.8253
1                Arizona     West   35282.0010  -3427.9246
2               Arkansas    South   11678.1300   4008.6871
3             California     West  457687.6315  76381.3871
4               Colorado     West   32108.1180  -6527.8579
5            Connecticut     East   13384.3570   3511.4918
6               Delaware     East   27451.0690   9977.3748
7   District of Columbia     East    2865.0200   1059.5893
8                Florida    South   89473.7080  -3399.3017
9                Georgia    South   49095.8400  16250.0433
10                 Idaho     West    4382.4860    826.7231
11              Illinois  Central   80166.1010 -12607.8870
12               Indiana  Central   53555.3600  18382.9363
13                  Iowa  Central    4579.7600   1183.8119
14                Kansas  Central    2914.3100    836.4435
15              Kentucky    South   36591.7500  11199.6966
16             Louisiana    South    9217.0300   2196.1023
17                 Maine     East    1270.5300    454.4862
18              Maryland     East   23705.5230   7031.1788
19         Massachusetts     East   28634.4340   6785.5016
20              Michigan  Central   76269.6140  24463.1876
21             Minnesota  Central   29863.1500  10823.1874
22           Mississippi    South   10771.3400   3172.9762
23              Missouri  Central   22205.1500   6436.2105
24               Montana     West    5589.3520   1833.3285
25              Nebraska  Central    7464.9300   2037.0942
26                Nevada     West   16729.1020   3316.7659
27         New Hampshire     East    7292.5240   1706.5028
28            New Jersey     East   35764.3120   9772.9138
29            New Mexico     West    4783.5220   1157.1161
30              New York     East  310876.2710  74038.5486
31        North Carolina    South   55603.1640  -7490.9122
32          North Dakota  Central     919.9100    230.1497
33                  Ohio     East   78258.1360 -16971.3766
34              Oklahoma  Central   19683.3900   4853.9560
35                Oregon     West   17431.1500  -1190.4705
36          Pennsylvania     East  116511.9140 -15559.9603
37          Rhode Island     East   22627.9560   7285.6293
38        South Carolina    South    8481.7100   1769.0566
39          South Dakota  Central    1315.5600    394.8283
40             Tennessee    South   30661.8730  -5341.6936
41                 Texas  Central  170188.0458 -25729.3563
42                  Utah     West   11220.0560   2546.5335
43               Vermont     East    8929.3700   2244.9783
44              Virginia    South   70636.7200  18597.9504
45            Washington     West  138641.2700  33402.6517
46         West Virginia     East    1209.8240    185.9216
47             Wisconsin  Central   32114.6100   8401.8004
48               Wyoming     West    1603.1360    100.1960

In [126]:
profit

                   State   Region        Sales      Profit
0                Alabama    South   19510.6400   5786.8253
1                Arizona     West   35282.0010  -3427.9246
2               Arkansas    South   11678.1300   4008.6871
3             California     West  457687.6315  76381.3871
4               Colorado     West   32108.1180  -6527.8579
5            Connecticut     East   13384.3570   3511.4918
6               Delaware     East   27451.0690   9977.3748
7   District of Columbia     East    2865.0200   1059.5893
8                Florida    South   89473.7080  -3399.3017
9                Georgia    South   49095.8400  16250.0433
10                 Idaho     West    4382.4860    826.7231
11              Illinois  Central   80166.1010 -12607.8870
12               Indiana  Central   53555.3600  18382.9363
13                  Iowa  Central    4579.7600   1183.8119
14                Kansas  Central    2914.3100    836.4435
15              Kentucky    South   36591.7500  11199.6966
16             Louisiana    South    9217.0300   2196.1023
17                 Maine     East    1270.5300    454.4862
18              Maryland     East   23705.5230   7031.1788
19         Massachusetts     East   28634.4340   6785.5016
20              Michigan  Central   76269.6140  24463.1876
21             Minnesota  Central   29863.1500  10823.1874
22           Mississippi    South   10771.3400   3172.9762
23              Missouri  Central   22205.1500   6436.2105
24               Montana     West    5589.3520   1833.3285
25              Nebraska  Central    7464.9300   2037.0942
26                Nevada     West   16729.1020   3316.7659
27         New Hampshire     East    7292.5240   1706.5028
28            New Jersey     East   35764.3120   9772.9138
29            New Mexico     West    4783.5220   1157.1161
30              New York     East  310876.2710  74038.5486
31        North Carolina    South   55603.1640  -7490.9122
32          North Dakota  Central     919.9100    230.1497
33                  Ohio     East   78258.1360 -16971.3766
34              Oklahoma  Central   19683.3900   4853.9560
35                Oregon     West   17431.1500  -1190.4705
36          Pennsylvania     East  116511.9140 -15559.9603
37          Rhode Island     East   22627.9560   7285.6293
38        South Carolina    South    8481.7100   1769.0566
39          South Dakota  Central    1315.5600    394.8283
40             Tennessee    South   30661.8730  -5341.6936
41                 Texas  Central  170188.0458 -25729.3563
42                  Utah     West   11220.0560   2546.5335
43               Vermont     East    8929.3700   2244.9783
44              Virginia    South   70636.7200  18597.9504
45            Washington     West  138641.2700  33402.6517
46         West Virginia     East    1209.8240    185.9216
47             Wisconsin  Central   32114.6100   8401.8004
48               Wyoming     West    1603.1360    100.1960

# What is the impact of discounts on profit across different product categories?

In [127]:
avg=v.groupby('Discount')[['Sales','Profit']].mean().reset_index()
print("/n3. Average impact of discount on profit")
print(avg)

/n3. Average impact of discount on profit
    Discount       Sales      Profit
0       0.00  226.742074   66.900292
1       0.10  578.397351   96.055074
2       0.15  529.971567   27.288298
3       0.20  209.076940   24.702572
4       0.30  454.742974  -45.679636
5       0.32  536.794770  -88.560656
6       0.40  565.134874 -111.927429
7       0.45  498.634000 -226.646464
8       0.50  892.705152 -310.703456
9       0.60   48.150000  -43.077212
10      0.70   97.177708  -95.874060
11      0.80   56.545853 -101.796797

# 4) are there any products that consistently generate losses despite good sales volume?

In [128]:
loss_products =v.groupby('Product Name')[['Sales','Profit']].sum().sort_values(by='Profit').head(10).reset_index()
print("/n4.Loss making products despite good sales")
print(loss_products)

/n4.Loss making products despite good sales
                                        Product Name      Sales     Profit
0          Cubify CubeX 3D Printer Double Head Print  11099.963 -8879.9704
1          Lexmark MX611dhe Monochrome Laser Printer  16829.901 -4589.9730
2          Cubify CubeX 3D Printer Triple Head Print   7999.980 -3839.9904
3  Chromcraft Bull-Nose Wood Oval Conference Tabl...   9917.640 -2876.1156
4  Bush Advantage Collection Racetrack Conference...   9544.725 -1934.3976
5          GBC DocuBind P400 Electric Binding System  17965.068 -1878.1662
6  Cisco TelePresence System EX90 Videoconferenci...  22638.480 -1811.0784
7  Martin Yale Chadless Opener Electric Letter Op...  16656.200 -1299.1836
8                       Balt Solid Wood Round Tables   6518.754 -1201.0581
9  BoxOffice By Design Rectangular and Half-Moon ...   1706.250 -1148.4375

# operational and shipping analysis

# 1) What is the average delivery time (Ship Date - Order Date) by Ship Mode, and how does it impact customer segment satisfaction?

In [129]:
avgshipmode=v.groupby('Ship Mode')['Delivery time'].mean().reset_index()
print("/n5. Average delivery time by ship mode")
print(avgshipmode)

/n5. Average delivery time by ship mode
        Ship Mode             Delivery time
0     First Class 2 days 04:23:05.695708712
1        Same Day 0 days 01:03:38.784530386
2    Second Class 3 days 05:42:47.197943444
3  Standard Class 5 days 00:09:24.611260053

 # 6 Which shipping modes are most frequently used, and how do they correlate with profit or loss?

In [130]:
shipmode=v.groupby('Ship Mode')[['Sales','Profit']].sum().reset_index()
print("\n.6 Most frequently used shipping models")
print(shipmode)

.6 Most frequently used shipping models
        Ship Mode         Sales       Profit
0     First Class  3.514284e+05   48969.8399
1        Same Day  1.283631e+05   15891.7589
2    Second Class  4.591936e+05   57446.6354
3  Standard Class  1.358216e+06  164088.7875


 #7) do sales and profits differ by shipping mode across regions?

In [131]:
ap=v.groupby(['Ship Mode','Region'])[['Sales','Profit']].sum().reset_index()
print("/n7. Shipping performance by region")
print(ap)

/n7. Shipping performance by region
         Ship Mode   Region        Sales      Profit
0      First Class  Central   58746.9154   3707.2672
1      First Class     East  113587.0530  15732.0141
2      First Class    South   49332.5660   6892.3854
3      First Class     West  129761.8885  22638.1732
4         Same Day  Central   20415.4100   1531.8797
5         Same Day     East   43326.8320   7980.2670
6         Same Day    South   21017.1730  -1762.3350
7         Same Day     West   43603.7100   8141.9472
8     Second Class  Central  103550.0054   9114.8349
9     Second Class     East  116545.5240  10787.2908
10    Second Class    South   93758.6125  14667.1469
11    Second Class     West  145339.4275  22877.3628
12  Standard Class  Central  318527.5600  25352.3807
13  Standard Class     East  405321.8310  57023.2081
14  Standard Class    South  227613.5535  26952.2330
15  Standard Class     West  406752.7985  54760.9657

#8 Which customer segments (Consumer, Corporate, Home Office) have the highest average order value?

In [132]:
from numpy._core.defchararray import count
aov = v.groupby('Segment').agg({'Sales': 'mean','Order ID':'count'})
print("\8. Customer segment with highest average order value")
print(aov)

\8. Customer segment with highest average order value
                  Sales  Order ID
Segment
Consumer     223.733644      5191
Corporate    233.823300      3020
Home Office  240.972041      1783

# 9 Top 10 profitable customerS

In [133]:
psc=v.groupby(['Customer ID','Customer Name'])[['Profit']].sum().sort_values(by ='Profit',ascending=False).reset_index().head(10)
print("\n9. TOP 10 profitable customers ")
print(psc)

9. TOP 10 profitable customers
  Customer ID         Customer Name     Profit
0    TC-20980          Tamara Chand  8981.3239
1    RB-19360          Raymond Buch  6976.0959
2    SC-20095          Sanjit Chand  5757.4119
3    HL-15040          Hunter Lopez  5622.4292
4    AB-10105         Adrian Barton  5444.8055
5    TA-21385          Tom Ashbrook  4703.7883
6    CM-12385  Christopher Martinez  3899.8904
7    KD-16495         Keith Dawkins  3038.6254
8    AR-10540           Andy Reiter  2884.6208
9    DR-12940         Daniel Raglin  2869.0760

# 10  10. Repeat customers and discount/profit

In [134]:
rc=v.groupby('Customer ID').agg({'Order ID':'nunique','Profit':'sum','Discount':'mean'}).reset_index()
print("\10. Repeat customer behaviour")
print(rc)

. Repeat customer behaviour
    Customer ID  Order ID     Profit  Discount
0      AA-10315         5  -362.8825  0.090909
1      AA-10375         9   277.3824  0.080000
2      AA-10480         4   435.8274  0.016667
3      AA-10645         6   857.8033  0.063889
4      AB-10015         3   129.3465  0.066667
..          ...       ...        ...       ...
788    XP-21865        11   621.2300  0.046429
789    YC-21895         5  1305.6290  0.075000
790    YS-21880         8  1778.2923  0.050000
791    ZC-21910        13 -1032.1490  0.254839
792    ZD-21925         5   249.1307  0.111111

[793 rows x 4 columns]

# 11. Monthly sales, profit, and discount trends

In [135]:
trends = v.groupby(['year','month'])[['Sales','Profit','Discount']].sum().reset_index()
print("\n11. Monthly sales,profit and discount trends")
print(trends)

11. Monthly sales,profit and discount trends
    year  month        Sales      Profit  Discount
0   2014      1   14236.8950   2450.1907     10.00
1   2014      2    4519.8920    862.3084      8.10
2   2014      3   55691.0090    498.7299     26.30
3   2014      4   28295.3450   3488.8352     14.85
4   2014      5   23648.2870   2738.7096     18.95
5   2014      6   34595.1276   4976.5244     23.22
6   2014      7   33946.3930   -841.4826     24.55
7   2014      8   27909.4685   5318.1050     20.05
8   2014      9   81777.3508   8328.0994     42.87
9   2014     10   31453.3930   3448.2573     25.45
10  2014     11   78628.7167   9292.1269     48.07
11  2014     12   69545.6205   8983.5699     53.05
12  2015      1   18174.0756  -3281.0070     10.32
13  2015      2   11951.4110   2813.8508      8.30
14  2015      3   38726.2520   9732.0978     19.34
15  2015      4   34195.2085   4187.4962     28.15
16  2015      5   30131.6865   4667.8690     24.25
17  2015      6   24797.2920   3335.5572     23.80
18  2015      7   28765.3250   3288.6483     23.85
19  2015      8   36898.3322   5355.8084     24.87
20  2015      9   64595.9180   8209.1627     41.30
21  2015     10   31404.9235   2817.3660     26.95
22  2015     11   75972.5635  12474.7884     52.59
23  2015     12   74919.5212   8016.9659     43.37
24  2016      1   18542.4910   2824.8233     11.80
25  2016      2   22978.8150   5004.5795      8.00
26  2016      3   51715.8750   3611.9680     31.12
27  2016      4   38750.0390   2977.8149     26.50
28  2016      5   56987.7280   8662.1464     41.50
29  2016      6   40344.5340   4750.3781     27.60
30  2016      7   39261.9630   4432.8779     32.05
31  2016      8   31115.3743   2062.0693     32.67
32  2016      9   73410.0249   9328.6576     54.24
33  2016     10   59687.7450  16243.1425     28.85
34  2016     11   79411.9658   4011.4075     58.32
35  2016     12   96999.0430  17885.3093     47.67
36  2017      1   43971.3740   7140.4391     25.00
37  2017      2   20301.1334   1613.8720     19.47
38  2017      3   58872.3528  14751.8915     31.14
39  2017      4   36521.5361    933.2900     39.47
40  2017      5   44261.1102   6342.5828     36.89
41  2017      6   52981.7257   8223.3357     42.12
42  2017      7   45264.4160   6952.6212     31.65
43  2017      8   63120.8880   9040.9557     31.30
44  2017      9   87866.6520  10991.5556     67.65
45  2017     10   77776.9232   9275.2755     51.92
46  2017     11  118447.8250   9690.1037     73.89
47  2017     12   83829.3188   8483.3468     67.72

# 12. Peak sales months
psm = trends.sort_values(by='Sales', ascending = False).head(10)
psm

In [136]:
psm = trends.sort_values(by='Sales', ascending = False).head(10)
print(psm)

    year  month        Sales      Profit  Discount
46  2017     11  118447.8250   9690.1037     73.89
35  2016     12   96999.0430  17885.3093     47.67
44  2017      9   87866.6520  10991.5556     67.65
47  2017     12   83829.3188   8483.3468     67.72
8   2014      9   81777.3508   8328.0994     42.87
34  2016     11   79411.9658   4011.4075     58.32
10  2014     11   78628.7167   9292.1269     48.07
45  2017     10   77776.9232   9275.2755     51.92
22  2015     11   75972.5635  12474.7884     52.59
23  2015     12   74919.5212   8016.9659     43.37

# 13. Sub-category sales per unit

In [137]:
value_per_unit = v.groupby('Sub-Category').agg({'Sales':'sum','Quantity':'sum'})
value_per_unit['Sales per unit']=value_per_unit['Sales']/value_per_unit['Quantity']
value_per_unit= value_per_unit.reset_index()
value_per_unit

   Sub-Category        Sales  Quantity  Sales per unit
0   Accessories  167380.3180      2976       56.243386
1    Appliances  107532.1610      1729       62.193268
2           Art   27118.7920      3000        9.039597
3       Binders  203412.7330      5974       34.049671
4     Bookcases  114879.9963       868      132.350226
5        Chairs  328449.1030      2356      139.409636
6       Copiers  149528.0300       234      639.008675
7     Envelopes   16476.4020       906       18.185874
8     Fasteners    3024.2800       914        3.308840
9   Furnishings   91705.1640      3563       25.738188
10       Labels   12486.3120      1400        8.918794
11     Machines  189238.6310       440      430.087798
12        Paper   78479.2060      5178       15.156278
13       Phones  330007.0540      3289      100.336593
14      Storage  223843.6080      3158       70.881446
15     Supplies   46673.5380       647       72.138389
16       Tables  206965.5320      1241      166.773193

# 14. Product combinations (market basket)

In [138]:
market=v.groupby('Order ID')['Product Name'].apply(lambda x:list(x)).reset_index
print("\n14. Product combinations")
print(market)

14. Product combinations
<bound method Series.reset_index of Order ID
CA-2014-100006                                  [AT&T EL51110 DECT]
CA-2014-100090    [Hon 2111 Invitation Series Corner Table, Wils...
CA-2014-100293                                         [Xerox 1887]
CA-2014-100328    [Pressboard Covers with Storage Hooks, 9 1/2" ...
CA-2014-100363    [Binder Clips by OIC, Things To Do Today Spira...
                                        ...
US-2017-168802                                       [Binder Posts]
US-2017-169320    [Quartet Omega Colored Chalk, 12/Pack, Memorex...
US-2017-169488    [Avoid Verbal Orders Carbonless Minifold Book,...
US-2017-169502    [Acme Stainless Steel Office Snips, Acco 6 Out...
US-2017-169551    [O'Sullivan 3-Shelf Heavy-Duty Bookcases, Xero...
Name: Product Name, Length: 5009, dtype: object>

# 15. Predicting profit using regression

In [146]:
x =v[['Sales','Quantity','Discount']]
y =v['Profit']
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)
model = LinearRegression().fit(xtrain,ytrain)
model_score =model.score(xtest,ytest)
model_score
print(f"\n15. Predictive model estimation:{model_score:.4f}")

15. Predictive model estimation:0.3448